# Notebook permettant la reconstruction 3D de la tumeur

In [5]:
############################ Import des modules necessaires #############################

import numpy as np
import matplotlib.pyplot as plt
from mayavi import mlab
import nibabel as nib

In [6]:
##########################

# Charger le masque 3D de la tumeur à partir du tableau NumPy
mask_4d = np.load("/Users/bimlaboratoire/python/stage_mzoughebi/notebook/PYTHON/archive/BraTS2020_TrainingData/input_data_128_2channels/train/masks/patient_0.npy")

# Vérifier les dimensions du masque
print(mask_4d.shape)  # Cela devrait afficher (128, 128, 128, 4)
mask_4d[mask_4d==4] = 3 ##LE LABEL 4 EST CHANGE EN 3

################################################################################
# mask_4d[:, :, :, 0] == Unlabeled volume / Brain = Green sprectral 
# mask_4d[:, :, :, 1] == Necrotic and non-enhancing tumor core (NCR/NET) - Green
# mask_4d[:, :, :, 2] == Peritumoral edema (ED) - Jaune
# mask_4d[:, :, :, 3] == Classe 4: GD-enhancing Tumor - Rouge
################################################################################

# Convertir en tableau à trois dimensions en n'utilisant que le premier canal (par exemple)
mask_3d = mask_4d[:, :, :, 3]
print(mask_3d)

# Convertir en tableau à trois dimensions en n'utilisant que le premier canal (par exemple)
mask_3d_oe = mask_4d[:, :, :, 2]

# Convertir en tableau à trois dimensions en n'utilisant que le premier canal (par exemple)
mask_3d_ne = mask_4d[:, :, :, 1]




# Vérifier les dimensions du masque 3D résultant
print(mask_3d.shape)  # Cela devrait afficher (128, 128, 128)

(128, 128, 128, 4)
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 

In [7]:
# Charger l'IRM du cerveau à partir du tableau NumPy (128x128x128) de luminance
irm_brain= nib.load('/Users/bimlaboratoire/python/stage_mzoughebi/notebook/PYTHON/archive/BraTS2020_TrainingData/MICCAI_BraTS2020_TrainingData/BraTS20_Training_001/BraTS20_Training_001_t1.nii').get_fdata()
irm_brain=irm_brain.astype(np.uint8)
# Convertir en tableau à trois dimensions en n'utilisant que le premier canal (par exemple)
print(irm_brain.shape)
irm_brain=irm_brain[56:184,56:184,13:141]
print(irm_brain.shape)

(240, 240, 155)
(128, 128, 128)


In [8]:
#########################


# Créez une figure Mayavi
fig = mlab.figure(size=(800, 800))

# Utilisez la fonction "contour3d" pour créer une visualisation 3D de la tumeur
contour_irm = mlab.contour3d(irm_brain, colormap="Spectral")

contour_irm.actor.property.opacity = 0.05 


# Utilisez la fonction "contour3d" pour créer une visualisation 3D de la tumeur
contour = mlab.contour3d(mask_3d, colormap="Reds")

# Vous pouvez ajouter des options supplémentaires pour personnaliser l'apparence
contour.actor.property.opacity = 0.4 # Réglez la transparence pour voir à travers la tumeur


# Utilisez la fonction "contour3d" pour créer une visualisation 3D de la tumeur
contour_oe = mlab.contour3d(mask_3d_oe, colormap="Blues")

# Vous pouvez ajouter des options supplémentaires pour personnaliser l'apparence
contour_oe.actor.property.opacity = 0.2 # Réglez la transparence pour voir à travers la tumeur


# Utilisez la fonction "contour3d" pour créer une visualisation 3D de la tumeur
contour_ne = mlab.contour3d(mask_3d_ne, colormap="Greens")

# Vous pouvez ajouter des options supplémentaires pour personnaliser l'apparence
contour_ne.actor.property.opacity = 0.6 # Réglez la transparence pour voir à travers la tumeur


# Afficher la figure
mlab.show()
